/**
 * Build-time generator for the sanguo emoji registry (D-13).
 *
 * Reads the sibling repo's emojis.json (E:\Saeth\sanguo_assets\assets\emojis.json
 * by default, override with env SANGUO_EMOJIS_SOURCE) and emits the committed
 * registry module src/assets/sanguoEmojis.ts.
 *
 * Runtime NEVER reads the sibling repo — the committed generated file is the
 * only runtime source of emoji data.
 *
 * Usage: npx tsx scripts/gen-sanguo-emojis.ts
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SOURCE_PATH = process.env.SANGUO_EMOJIS_SOURCE ?? 'E:\\Saeth\\sanguo_assets\\assets\\emojis.json';
const OUT_PATH = path.join(__dirname, '../src/assets/sanguoEmojis.ts');
const MIN_HERO_PREFIXES = 132;
// Key shape: '<hero_id>_t<tier>[_star]' — e.g. abt_t0, abt_t3_star
const KEY_PATTERN = /^[a-z0-9_]+_t[0-3](_star)?$/;

interface EmojisFile {
  applicationId: string;
  emojis: Record<string, string>;
}

function fail(message: string): never {
  console.error(`❌ gen-sanguo-emojis: ${message}`);
  process.exit(1);
}

function loadSource(): EmojisFile {
  let raw: string;
  try {
    raw = readFileSync(SOURCE_PATH, 'utf-8');
  } catch (err) {
    fail(`cannot read source file ${SOURCE_PATH} — ${(err as Error).message}`);
  }
  let data: EmojisFile;
  try {
    data = JSON.parse(raw) as EmojisFile;
  } catch (err) {
    fail(`source file is not valid JSON: ${(err as Error).message}`);
  }
  if (!data || typeof data !== 'object' || typeof data.applicationId !== 'string' || !data.emojis) {
    fail('source file must contain top-level applicationId (string) and emojis (object)');
  }
  // Discord snowflakes are 17-20 digit unsigned 64-bit ids (the D-16 value is 19 digits)
  if (!/^\d{17,20}$/.test(data.applicationId)) {
    fail(`applicationId "${data.applicationId}" is not a valid Discord application id (17-20 digits)`);
  }
  return data;
}

function validateEmojis(emojis: Record<string, string>): void {
  const entries = Object.entries(emojis);
  for (const [key, value] of entries) {
    if (!KEY_PATTERN.test(key)) {
      fail(`emoji key "${key}" does not match pattern <hero_id>_t<tier>[_star]`);
    }
    if (!/^\d{17,20}$/.test(value)) {
      fail(`emoji value for "${key}" ("${value}") is not a valid Discord emoji id`);
    }
  }
  const prefixes = new Set<string>();
  for (const key of Object.keys(emojis)) {
    prefixes.add(key.replace(/_t[0-3](_star)?$/, ''));
  }
  if (prefixes.size < MIN_HERO_PREFIXES) {
    fail(`only ${prefixes.size} distinct hero prefixes — expected at least ${MIN_HERO_PREFIXES}`);
  }
}

function renderKeyLines(emojis: Record<string, string>): string[] {
  return Object.keys(emojis)
    .sort() // deterministic: stable sorted order → idempotent output
    .map((key) => `  ${key}: '${emojis[key]}',`);
}

function renderFile(applicationId: string, emojis: Record<string, string>): string {
  const keyLines = renderKeyLines(emojis);
  return `/* eslint-disable i18next/no-literal-string -- generated emoji registry: IDs are machine data, not UI strings */
// Generated by scripts/gen-sanguo-emojis.ts — DO NOT EDIT BY HAND.
// Source: sibling repo emojis.json (dev-time only; runtime never reads it — D-13)

export const SANSUO_EMOJI_APPLICATION_ID = '${applicationId}' as const;

export const SANSUO_EMOJIS = {
${keyLines.join('\n')}
} as const;

export type SanguoEmojiKey = keyof typeof SANSUO_EMOJIS;
export type SanguoTier = 0 | 1 | 2 | 3;

/**
 * Sole render point for sanguo emoji (D-15).
 * Returns renderable Discord markup '<:name:id>' — Discord renders custom/app
 * emoji ONLY via this markup; a bare id would render as literal text (SC3).
 * Missing tier variant falls back to the hero's t0 entry; a heroId with no
 * prefix in the registry throws — never returns '' or a raw literal.
 */
export function heroEmoji(heroId: string, tier: SanguoTier = 0, star = false): string {
  const requestedKey = \`\${heroId}_t\${tier}\${star ? '_star' : ''}\` as SanguoEmojiKey;
  const resolvedKey: SanguoEmojiKey =
    SANSUO_EMOJIS[requestedKey] !== undefined
      ? requestedKey
      : (\`\${heroId}_t0\` as SanguoEmojiKey);
  const id = SANSUO_EMOJIS[resolvedKey];
  if (id === undefined) {
    throw new Error(\`EMOJI_NOT_FOUND:\${heroId}\`);
  }
  return \`<:\${resolvedKey}:\${id}>\`;
}

/** Pure startup contract (D-14): registry applicationId must equal CLIENT_ID. */
export function assertEmojiApplicationId(registryAppId: string, clientId: string): boolean {
  return registryAppId === clientId;
}
`;
}

// --- main ---
const source = loadSource();
validateEmojis(source.emojis);

const output = renderFile(source.applicationId, source.emojis);
mkdirSync(path.dirname(OUT_PATH), { recursive: true });
writeFileSync(OUT_PATH, output, 'utf-8');

const count = Object.keys(source.emojis).length;
const prefixes = new Set(Object.keys(source.emojis).map((k) => k.replace(/_t[0-3](_star)?$/, '')));
console.log(`✅ Wrote ${OUT_PATH} (${count} emoji keys, ${prefixes.size} hero prefixes, applicationId ${source.applicationId})`);
